# Generated by Django 4.2.5 on 2023-09-13 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0002_alter_post_body_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='owner',
            new_name='user',
        ),
    ]
