# Generated by Django 4.2.5 on 2023-09-19 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 10, 48, 15, 885815)),
        ),
    ]
