# Generated by Django 4.2.5 on 2023-09-19 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 14, 32, 46, 153716)),
        ),
    ]
