# Generated by Django 4.2.5 on 2023-09-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdata_address_userdata_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='phone',
        ),
    ]
